# -*- coding: utf-8 -*-
"""TP.1

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1eJ7Wv3N4mXpU_YnTmChf3CRGNrFbinra
"""

# Commented out IPython magic to ensure Python compatibility.
# %%writefile gastos.py
# # Lista donde se guardan los gastos
# gastos = []
# 
# # Función para agregar un gasto
# def agregar_gasto(gastos, descripcion, monto):
#     gasto = {
#         "descripcion": descripcion,
#         "monto": monto
#     }
#     gastos.append(gasto)
# 
# # Función para calcular el total
# def calcular_total(gastos):
#     total = 0
# 
#     for gasto in gastos:
#         total += gasto["monto"]
# 
#     return total
# 
# # Función para mostrar los gastos
# def mostrar_gastos(gastos):
#     return gastos

# Commented out IPython magic to ensure Python compatibility.
# %%writefile app.py

!mkdir templates

# Commented out IPython magic to ensure Python compatibility.
# %%writefile templates/index.
# <!DOCTYPE html>
# <html lang="es">
# <head>
#     <meta charset="UTF-8">
#     <title>Registro de Gastos</title>
# </head>
# <body>
# 
# <h1>Registro de Gastos</h1>
# 
# <form action="/agregar" method="POST">
# 
# <label>Descripción:</label>
# <input type="text" name="descripcion" required>
# 
# <br><br>
# 
# <label>Monto:</label>
# <input type="number" step="0.01" name="monto" required>
# 
# <br><br>
# 
# <button type="submit">Agregar gasto</button>
# 
# </form>
# 
# <hr>
# 
# <h2>Lista de gastos</h2>
# 
# {% if gastos %}
# 
# <ul>
# 
# {% for gasto in gastos %}
# 
# <li>{{ gasto.descripcion }} - ${{ gasto.monto }}</li>
# 
# {% endfor %}
# 
# </ul>
# 
# <p><strong>Total gastado: ${{ total }}</strong></p>
# 
# {% else %}
# 
# <p>No hay gastos registrados.</p>
# 
# {% endif %}
# 
# </body>
# </html>